project:
  type: website

website:
  title: "Lela Roos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    pinned: FALSE
    

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual


